# Generated by Django 2.2.8 on 2019-12-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_auto_20191209_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='steam.Developer'),
            preserve_default=False,
        ),
    ]
