# Generated by Django 2.2.8 on 2019-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0004_auto_20191209_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='logo',
            field=models.CharField(default='image', max_length=200),
            preserve_default=False,
        ),
    ]
